version: '3.3'

services:

### MySQL Container #########################################
    mysql:
        build: 
            context: ./mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"

### Wordpress Container #########################################
    wordpress:
        build:
            context: ./wordpress
        environment:
            - WORDPRESS_DB_HOST=mysql:${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
        depends_on:
            - mysql
        ports:
            - "8000:80"
        restart: always

### Volumes Setup #############################################

volumes:
    mysql:
        driver: "local"



